l_russian:
 PRODUCTION_PRODUCTION_LABEL:0 "Производство"
 PRODUCTION_EQUIPMENTPOOL_LABEL:0 "Склад"
 PRODUCTION_EFFICIENCY_LABEL:0 "§TЭффективность§!"
 PRODUCTION_EQUIPMENT_LABEL:0 "Техника"
 PRODUCTION_ADJUSTERS_LABEL:0 "Модификаторы"
 PRODUCTION_MATERIALS_LABEL:0 "Материалы"
 PRODUCTION_FACTORIES_LABEL:0 "Фабрики"
 PRODUCTION_OPERATIONAL_ARMS_FACTORIES_LABEL:0 "Военные заводы"
 PRODUCTION_OPERATIONAL_DOCKYARDS_LABEL:0 "Верфи"
 PRODUCTION_OPERATIONAL_FACTORIES_LABEL:0 "Фабрики"
 PRODUCTION_AVAILABLE_ARMS_FACTORIES_LABEL:0 "Доступные военные заводы"
 PRODUCTION_AVAILABLE_DOCKYARDS_LABEL:0 "Доступные верфи"
 PRODUCTION_AVAILABLE_FACTORIES_LABEL:0 "Доступные фабрики"
 PRODUCTION_OPERATIONAL_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 PRODUCTION_MILITARY_LABEL:0 "§TСнаряжение армии и ВВС§!"
 PRODUCTION_NAVAL_LABEL:0 "§TСнаряжение флота§!"
 PRODUCTION_BUILDINGS_LABEL:0 "§TСтроительство сооружений§!"
 PRODUCTION_PRODUCING_DAILY:0 "$AMOUNT$/день"
 PRODUCTION_PRODUCING_WEEKLY:0 "$AMOUNT$/неделя"
 PRODUCTION_PRODUCING_MONTHLY:0 "$AMOUNT$/месяц"
 PRODUCTION_PRODUCING_YEARLY:0 "$AMOUNT$/год"
 PRODUCTION_PRODUCING_ETA_DATE:0 "Завершение следующего: $DATE$"
 PRODUCTION_REPAIRING_ETA_DATE:0 "Завершение ремонта: $DATE$"
 PRODUCTION_PRODUCING_ETA_DAYS:0 "Через $AMOUNT$ дн."
 PRODUCTION_PRODUCING_ETA_WEEKS:0 "Через $AMOUNT$ нед."
 PRODUCTION_PRODUCING_ETA_MONTHS:0 "Через $AMOUNT$ мес."
 PRODUCTION_PRODUCING_ETA_YEARS:0 "Через $AMOUNT$ г."
 PRODUCTION_PRODUCING_NEVER:0 "§RНикогда§!"
 PRODUCTION_PRODUCING_NO_FACTORIES:0 "§RНет прикрепленных фабрик§!"
 PRODUCTION_PRODUCING_NONE:0 "§RНет§!"
 PRODUCTION_CAN_NOT_DEPLOY:0 "§RНевозможно разместить§!"
 PRODUCTION_CAN_NOT_DEPLOY_MANPOWER:0 "Недостаточно людских ресурсов"
 PRODUCTION_INCREASE_PRIORITY_LABEL:0 "§GЩелкните§H, чтобы поднять приоритет§!.\nShift+щелчок устанавливает §Hмаксимальный приоритет§! для производства.§!"
 PRODUCTION_DECREASE_PRIORITY_LABEL:0 "§GЩелкните§H, чтобы понизить приоритет§!.\nShift+щелчок устанавливает §Hминимальный приоритет§! для производства.§!"
 PRODUCTION_PRIORITY_DELAYED:0 "Производственная линия с более высоким приоритетом получает доступ к ресурсам раньше, чем линии с меньшим приоритетом."
 PRODUCTION_EFFICIENCY:0 "£prod_eff §TЭффективность производства: $AMOUNT|H2%$§!"
 PRODUCTION_EFFICIENCY_MOD:0 "£prod_eff §TЭффективность производства: $AMOUNT|Y2%$§!\n"
 PRODUCTION_EFFICIENCY_WITH_GAIN:0 "£prod_eff §TЭффективность производства: $AMOUNT|H2%$§! ($GAIN|H3%$ в день)"
 PRODUCTION_EFFICIENCY_DESC:0 "§TСредняя эффективность производства фабрики.\nЭффективность производства возрастает на $VALUE|H=2$% за единицу, равномерно распределенные по всем действующим фабрикам.§!"
 PRODUCTION_RESOURCE_PENALTY:0 "§TНехватка ресурсов: $AMOUNT|R2%$§!"
 PRODUCTION_ASSIGN_EQUIPMENT:0 "§TВыберите оборудование, чтобы начать производство.§!"
 PRODUCTION_MATERIALS_OIL:0 "Нефть"
 PRODUCTION_MATERIALS_ALUMINIUM:0 "Алюминий"
 PRODUCTION_MATERIALS_RUBBER:0 "Резина"
 PRODUCTION_MATERIALS_CHROMIUM:0 "Хром"
 PRODUCTION_MATERIALS_STEEL:0 "Сталь"
 PRODUCTION_MATERIALS_TUNGSTEN:0 "Вольфрам"
 PRODUCTION_MATERIAL_VAL:0 "$VALUE|0H$"
 PRODUCTION_VEHICLES_BUTTON:0 "Производство бронетехники"
 PRODUCTION_VEHICLES_BUTTON_DISABLED:0 "Бронетехника §Rне изобретена§!!"
 PRODUCTION_VEHICLES_BUTTON_NO_FACTORIES_DISABLED:0 "У нас §Rнет военных заводов!§!"
 PRODUCTION_INFANTRY_BUTTON:0 "Производство техники для пехоты и артиллерии"
 PRODUCTION_INFANTRY_BUTTON_DISABLED:0 "Техника для пехоты и артиллерии §Rне изобретена§!!"
 PRODUCTION_INFANTRY_BUTTON_NO_FACTORIES_DISABLED:0 "У нас §Rнет военных заводов!§!"
 PRODUCTION_AIRCRAFT_BUTTON:0 "Производство самолетов"
 PRODUCTION_AIRCRAFT_BUTTON_DISABLED:0 "Самолеты §Rне изобретены§!!"
 PRODUCTION_AIRCRAFT_BUTTON_NO_FACTORIES_DISABLED:0 "У нас §Rнет военных заводов§!!"
 PRODUCTION_SHIPS_BUTTON:0 "Производство кораблей"
 PRODUCTION_SHIPS_BUTTON_DISABLED:0 "Корабли §Rне изобретены§!!"
 PRODUCTION_SHIPS_BUTTON_NO_DEPLOY_DISABLED:0 "У нас §Rнет портов§!!"
 PRODUCTION_SHIPS_BUTTON_NO_FACTORIES_DISABLED:0 "У нас §Rнет верфей§!!"
 PRODUCTION_CONSUMER_GOODS_VALUE:0 "$VALUE$"
 PRODUCTION_CONSUMER_GOODS:0 "Потребительские товары"
 PRODUCTION_CONSUMER_GOODS_LABEL:0 "§HПотребительские товары§!"
 PRODUCTION_CONSUMER_GOODS_DESC:0 "В условиях текущей экономической политики граждане ожидают, что $PERCENTAGE|H0%$ от общего количества наших фабрик будут выпускать потребительские товары. Они справляются с этим требованием, поэтому у нас есть фабрики в кол-ве $OPERATIONAL|H$, где для торговли можно использовать $TRADE_USABLE|H$."
 PRODUCTION_CIV_AND_MIL_FACTORIES:0 "Фабрики и военные заводы: $KEY|H$"
 PRODUCTION_REQ_CONSUMER_GOODS_FACTORIES:0 "Необходимо фабрик для выпуска потребительских товаров: $KEY|H$"
 PRODUCTION_MATERIAL_COST_DESC:0 "§TЭто производство использует $AMOUNT|0H$ ед. ресурса $MATERIAL|H$.§!"
 PRODUCTION_MATERIAL_COST_LACKING_DESC:0 "§TНеобходимо еще $AMOUNT|0H$ ед. для полной эффективности.§!\nПроизводство продолжится со §Rсниженной скоростью§!."
 PRODUCTION_LINE_CANCEL:0 "§GЩелкните, чтобы §Hотменить§! эту производственную линию§!\n§GShift+щелчок - §Hотменить§! все производственные линии§!"
 PRODUCTION_CREATE_VARIANT:0 "§HСоздать вариант§!"
 PRODUCTION_CANCEL_CONSTRUCTION:0 "§TОтменить это строительство.§!"
 PRODUCTION_VARIANT_OBSOLETE_YES:0 "Повторный ввод в эксплуатацию"
 PRODUCTION_VARIANT_OBSOLETE_NO:0 "Вывод из эксплуатации"
 PRODUCTION_VARIANT_OBSOLETE_YES_DESC:0 "§GЩелкните§!, чтобы повторно ввести в эксплуатацию этот вариант, отметив его как современный вид техники."
 PRODUCTION_VARIANT_OBSOLETE_NO_DESC:0 "§GЩелкните§!, чтобы вывести из эксплуатации этот вариант, отметив его как устаревший вид техники."
 TRADE_FACTORIES_VALUE:0 "$VALUE$/$TOT$"
 CONFIRMCANCELPRODUCTIONLINE_TITLE:0 "Отменить производство"
 CONFIRMCANCELPRODUCTIONLINE_DESC:0 "Вы действительно хотите §Rотменить§! это производство?"
 CONFIRMCANCELALLPRODUCTIONLINE_TITLE:0 "Отменить все линии"
 CONFIRMCANCELALLPRODUCTIONLINE_DESC:0 "Вы действительно хотите §Rотменить§! все производственные линии?"
 CONFIRM_SWITCH_PRODUCTION_MODEL_TITLE:0 "Заменить оснащение"
 CONFIRM_SWITCH_PRODUCTION_MODEL_DESC:0 "Вы действительно хотите §Rзаменить§! оснащение? Вы потеряете $DAYS|R$ дн. производства."
 CONFIRMCANCELCONSTRUCTION_TITLE:0 "Отменить строительство"
 CONFIRMCANCELCONSTRUCTION_DESC:0 "Вы действительно хотите §Rотменить§! строительство $CONSTRUCTION|H$ в регионе $REGION|H$?"
 CONFIRMCANCELCONSTRUCTIONS_TITLE:0 "Отменить все стройки"
 CONFIRMCANCELCONSTRUCTIONS_DESC:0 "Вы действительно хотите §Rотменить§! все стройки?"
 INFINITY:0 "£infinity_icon"
 PRODUCTION_EQUIPMENT_NEED:0 "Необходимо: $AMOUNT|Y$"
 PRODUCTION_DEPLOY_TO_BASE:0 "Разместить в порту: $BASE|H$"
 PRODUCTION_DEPLOY_TO_FLEET:0 "Разместить на флоте: $FLEET|H$"
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET_INVALID_BASE:0 "У выбранного для размещения флота $FLEET|H$ нет базы."
 PRODUCTION_NAVAL_DEPLOYMENT_FLEET:0 "Выбранный для размещения флот $FLEET|H$ с базой в регионе $STATE|H$."
 PRODUCTION_NAVAL_DEPLOYMENT_BASE:0 "Выбранная для размещения база в регионе $STATE|H$."
 PRODUCTION_NAVAL_DEPLOYMENT_INVALID_BASE:0 "Не указана цель для размещения."
 PRODUCTION_NAVAL_DEPLOYMENT_NOT_DEPLOYABLE:0 "Невозможно разместить"
 PRODUCTION_NAVAL_DEPLOYMENT_AUTO_DEPLOYMENT:0 "Авто"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING:0 "Списание в утиль"
 PRODUCTION_NAVAL_DEPLOYMENT_SCRAPPING_DESC:0 "Нет подходящей базы для размещения. Боевая единица будет списана в утиль после выпуска."
 PRODUCTION_NAVAL_DEPLOYMENT_STOCKPILING:0 "Накопление"
 PRODUCTION_RIGHT_CLICK_TO_ZOOM:0 "§GЩелкните правой кнопкой, чтобы перейти к провинции§!"
 WEEKLY_PRODUCTION:0 "Еженедельное производство"
 PRODUCTION_WORKING_FACTORIES:0 "Количество фабрик, задействованных в одном или нескольких производствах."
 PRODICTION_MIC_TRANSFERED:0 "Количество фабрик, которые использует $OVERLORD|Y$: $AMOUNT|Y$."
 PRODICTION_MIC_RECEIVED_FROM_SUBJECT:0 "Количество военных заводов, полученных от наших субъектов: $AMOUNT|Y$."
 PRODICTION_MIC_SENT_TO_OVERLORD:0 "Количество военных заводов, переданных нами метрополии: $AMOUNT|R$. У нас осталось всего лишь $LEFT|H$."
 PRODUCTION_CIVILIAN_FACTORIES_AVAILABLE:0 "Доступно для строительства: $VALUE|Y$"
 PRODUCTION_CIVILIAN_FACTORIES_CURRENTLY:0 "Задействовано: $VALUE|R$"
 PRODUCTION_MAX_EFFICIENCY_BASE:0 "Базовый лимит: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_TOT:0 "£prod_eff_cap  Макс. эффективность производства: $VALUE|Y%$"
 PRODUCTION_MAX_EFFICIENCY_HINT:0 "£prod_eff_cap  Максимальная эффективность производства определяет максимальное значение вашей £prod_eff  эффективности производства. Ее можно увеличить путем изучения новых £tech_mod технологий."
 PRODUCTION_RESOURCES_PER_FACTORY:0 "§HОбъем производственных ресурсов для каждой фабрики:§!"
 PRODUCTION_MATERIAL_NO_WASTE:0 "Производство не расходует этот ресурс впустую."
 PRODUCTION_MATERIAL_WASTE:0 "Производство расходует впустую $WASTE|R2$ ед. этого ресурса."
 PRODUCTION_SPEED:0 "Скорость производства: $SPEED|Y$"
 PRODUCTION_SPEED_MODIFIERS:0 "§YФакторы, влияющие на объем производства:§!"
 INDUSTRIAL_CAPACITY_FACTOR:0 "Производительность фабрики: $VALUE|Y$"
 INDUSTRIAL_CAPACITY_FACTOR_MODIFIERS:0 "Факторы, влияющие на производительность фабрики:"
 INDUSTRIAL_PROGRESS:0 "$BUILDING|H$: выполнено $PROGRESS|0H$/$COST|0H$ ($VALUE|0%H$)."
 INDUSTRIAL_PROGRESS_REPAIR:0 "$BUILDING|H$: отремонтировано $PROGRESS|%0H$"
 INDUSTRIAL_BASE_FACTORY_OUTPUT:0 "Базовая производительность фабрики: $VALUE|H$"
 INDUSTRIAL_BASE_SPEED:0 "Выпуск продукции $FACTORIES|0H$ фабриками: $VALUE|H$"
 PROD_COST_VALUE:0 "£production_cost  $VALUE$"
 NAVPROD_COST_VALUE:0 "£navprod_cost  $VALUE$"
 PRODUCTION_CIVILIAN_FACTORIES_OWNED:0 "Во владении: $VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_BORROWED:0 "От экспорта: +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_SUBJECTS:0 "От субъектов: +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_MASTER:0 "Передано метрополии: $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_FROM_OTHERS:0 "От остальных стран: +$VAL|H$"
 PRODUCTION_CIVILIAN_FACTORIES_SENT_TO_OTHERS:0 "Передано остальным странам: $VAL|R$"
 PRODUCTION_CIVILIAN_FACTORIES_DAMAGED:0 "Повреждено: $VAL|R$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED:0 "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_FILLED:0 "$AMOUNT|0G$"
 PRODUCTION_EQUIPMENT_TOTAL_NEED_UPGRADE:0 "$VALUE|0Y$"
 PRODUCTION_EQUIPMENT_DAILY_BALANCE:0 "Ежедневный баланс: $VALUE|=2Y$"
 PRODUCTION_EQUIPMENT_FILL_ESTIMATION:0 "Соблюдая текущий ежедневный баланс, мы §Yудовлетворим§! наши потребности через $VALUE|0Y$ дн."
 PRODUCTION_EQUIPMENT_FILLED:0 "Наши потребности сейчас §Gудовлетворены§!."
 PRODUCTION_EQUIPMENT_LOSSES:0 "Вчера мы потеряли $VALUE|R$ ед. оборудования."
 PROD_LINE_PLANE_DEST_RESERVES:0 "Перенаправляются в §Yрезерв§!"
 PROD_LINE_PLANE_DEST_UPGRADING:0 "Необходимы для §Yмодернизации§!"
 PROD_LINE_PLANE_DEST_REINFORCEMENT:0 "Необходимы для §Yпополнения§!"
 PROD_LINE_LAND_DEST_RESERVES:0 "Откладываются в §Yзапасы§!"
 PROD_LINE_LAND_DEST_UPGRADING:0 "Необходимы для §Yмодернизации§!"
 PROD_LINE_LAND_DEST_REINFORCEMENT:0 "Необходимы для §Yпополнения§!"
 CONFIRM_REMOVE_BUILDING_LEVEL_TITLE:0 "Убрать сооружение"
 CONFIRM_REMOVE_BUILDING_LEVEL_DESC:0 "Вы действительно хотите §Rубрать§! это сооружение?"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_TITLE:0 "Отменить строительство"
 CONFIRM_REMOVE_CONSTRUCTION_LEVEL_DESC:0 "Вы действительно хотите §Rотменить§! это строительство?"
 CONFIRM_REMOVE_CONVERSION_LEVEL_TITLE:0 "Отменить конверсию"
 CONFIRM_REMOVE_CONVERSION_LEVEL_DESC:0 "Вы действительно хотите §Rотменить§! эту конверсию?"
 CONFIRM_ADD_CONVERSION_LEVEL_TITLE:0 "Начать конверсию"
 CONFIRM_ADD_CONVERSION_LEVEL_DESC:0 "Вы действительно хотите §Rпереоборудовать§! это сооружение?"
 PRODUCTION_EFFICIENCY_GAIN_BASE:0 "Ежедневный базовый прирост: $VAL|%Y$"
 PRODUCTION_RESOURCE_FACTOR:0 "Нехватка ресурсов: $VAL|%+$"
 PRODUCTION_OUTPUT_EXPLAIN:0 "Объем выпуска наших £factory_item  $FACTORIES|Y$ военных заводов - £production_cost $OUTPUT|Y$.\n$ITEM|Y$ обходится в £production_cost $ITEM_COST|2Y$, а значит, мы можем выпускать $PERTIMEPERIOD$.\n"
 PRODUCTION_OUTPUT_EXPLAIN_NAVAL:0 "Объем выпуска наших £naval_factory_icon  $FACTORIES|Y$ верфей - £navprod_cost $OUTPUT|Y$.\n$ITEM|Y$ обходится в £navprod_cost $ITEM_COST|2Y$, а значит, мы можем выпускать $PERTIMEPERIOD$.\n"
 PRODUCTION_UNITS_PER_DAY:0 "$UNITS|Y$ ед. в день"
 PRODUCTION_UNITS_PER_WEEK:0 "$UNITS|Y$ ед. в неделю"
 PRODUCTION_UNITS_PER_MONTH:0 "$UNITS|Y$ ед. в месяц"
 PRODUCTION_UNITS_PER_YEAR:0 "$UNITS|Y$ ед. в год"
 PRODUCTION_FACTORY_ASSIGN_DESC:0 "Щелкните, чтобы прикрепить к этому производству £factory_item $FACTORIES|Y$ §Yвоенных заводов§!. Базовый объем выпуска составит в этом случае £production_cost $OUTPUT|Y$ ед. в сутки.\nНа общий объем выпуска будут влиять §Yресурсы§!, §Yэффективность производства§! и другие §Yпроизводственные коэффициенты§!."
 PRODUCTION_DOCKYARD_ASSIGN_DESC:0 "Щелкните, чтобы прикрепить к этому производству £naval_factory_icon $FACTORIES|Y$ §Yверфей§!. Базовый объем выпуска составит в этом случае £navprod_cost $OUTPUT|Y$ ед. в сутки.\nНа общий объем выпуска будут влиять §Yресурсы§! и другие §Yпроизводственные коэффициенты§!."
 PRODUCTION_BASE_OUTPUT:0 "Базовый объем выпуска: $VALUE|Y$ x $MUL|Y$"
 PRODUCTION_EFF_GAIN_HINT:0 "§YНа скорость прироста эффективности влияют:§!"
 CARRIER_AIR_WING_COMPOSITION_TITLE:0 "Задать стандартный состав авиакрыльев для этого авианосца"
 CARRIER_AIR_WING_LIMIT_UNDER:0 "$COUNT|Y$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_MATCH:0 "$COUNT|G$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_OVER:0 "$COUNT|R$/$LIMIT$"
 CARRIER_AIR_WING_LIMIT_DESC:0 "Самолеты/вместимость авианосца"
 CARRIER_AIR_WING_LIMIT_DESC_UNDER:0 "§YЭтот авианосец заполнен не целиком§!"
 CARRIER_AIR_WING_LIMIT_DESC_OVER:0 "§RЭтот авианосец будет переполнен, а размещенные на нем авиакрылья получат штраф§!"
 CARRIER_AIR_WING_INCREASE:0 "Увеличить количество\n§GCtrl+щелчок, чтобы увеличить на§!§H5§!\n§GShift+щелчок, чтобы увеличить на §!§H10§!"
 CARRIER_AIR_WING_DECREASE:0 "Уменьшить количество\n§GCtrl+щелчок, чтобы уменьшить на§!§H5§!\n§GShift+щелчок, чтобы уменьшить на §!§H10§!"
 PRODUCTION_ENTRY_NEW:0 "§GНОВОЕ§!"
 PRODUCTION_ENTRY_OUTDATED:0 "§HУСТАРЕВШЕЕ§!"
 PRODUCTION_LINE_CHANGE:0 "§GЩелкните, чтобы §Hизменить§! тип выпускаемой техники.\nВы сохраните часть эффективности, если переключитесь на новую версию той же техники.\n§!§RВесь прогресс этой линии будет утерян.§!"
 PRODUCTION_LINE_CHANGE_NAVAL:0 "§GЩелкните, чтобы §Hизменить§! тип выпускаемой техники.\n§!§RВесь прогресс этой линии будет утерян.§!"
 PRODUCTION_EQUIPMENT_FILTER:0 "Техника для пехоты и артиллерии"
 PRODUCTION_ARMOR_FILTER:0 "Бронетехника"
 PRODUCTION_AIR_FILTER:0 "Авиация"
 PRODUCTION_CAPITAL_SHIPS_FILTER:0 "Крупные корабли"
 PRODUCTION_SCREEN_SHIPS_FILTER:0 "Корабли охранения"
 PRODUCTION_OTHER_SHIPS_FILTER:0 "Остальные корабли"
 PRODUCTION_LACKING_RESOURCES_FILTER:0 "Достаточность ресурсов"
 PRODUCTION_STOCKPILING_FILTER:0 "Накопление"
 PRODUCTION_REINFORCING_FILTER:0 "Пополнение"
 PRODUCTION_UPGRADING_FILTER:0 "Улучшение"
 PRODUCTION_OUTDATED_FILTER:0 "Современные модели"
 PRODUCTION_FILTER_CLICK_TO_HIDE:0 "§GЩелкните§!, чтобы §Rскрыть§! всю эту категорию."
 PRODUCTION_FILTER_CLICK_TO_SHOW:0 "§GЩелкните§!, чтобы §Gпоказать§! всю эту категорию."
 PRODUCTION_FILTER_SHIFTCLICK:0 "\n§GShift+щелчок§!, чтобы §Rскрыть§! всё."
 PRODUCTION_FILTER_SHIFTCLICK_AGAIN:0 "\n§GShift+щелчок§! – снова §Gпоказать§! все."
 PRODUCTION_FILTER_RIGHTCLICK:0 "\n§GЩелкните правой кнопкой§!, чтобы свернуть или развернуть всю эту категорию."
 PRODUCTION_FILTER_ARMS_FACTORIES:0 "Используются военные заводы"
 PRODUCTION_FILTER_DOCKYARDS:0 "Используются верфи"
 PRODUCTION_DRAG_N_DROP:0 "§GПеретаскивайте курсором§!, чтобы изменить §Yприоритет§!."
 PRODUCTION_COLLAPSE:0 "§GЩелкните§!, чтобы §Yсвернуть§!."
 PRODUCTION_EXPAND:0 "§GЩелкните§!, чтобы §Yразвернуть§!."
 PRODUCTION_FACTORY_SCALE_UP:0 "§GЩелкните§!, чтобы изменить масштаб обзора до §Y$SCALE$x§!."
 PRODUCTION_FACTORY_SCALE_DOWN:0 "§GЩелкните§! еще раз, чтобы вернуть масштаб §Y1x§!."
 PRODUCTION_ADD_FACTORIES_CLICK:0 "§GЩелкните§!, чтобы добавить §Y1§!\n§GCtrl + щелчок§! — добавить §Y5§!\n§GShift + шелчок§! — добавить §Y10§!"
 PRODUCTION_SUB_FACTORIES_CLICK:0 "§GЩелкните§!, чтобы уменьшить на §Y1§!\n§GCtrl + щелчок§! — уменьшить на §Y5§!\n§GShift + щелчок§! — уменьшить на §Y10§!"
 PRODUCTION_CLICK_TO_APPEND_OR_INSERT:0 "§GЩелкните§!, чтобы добавить новую производственную линию в конец.\n§GShift + щелчок§! — добавить новую производственную линию сверху."
 PRODUCTION_NAVAL_DEPLOYMENT_STATE_NAME:0 "$STATE$ ($LVL|Y$)"
 PRODUCTION_LINE_CONVERT_NO_EQUIPMENT_IN_STOCK:0 "§RВ нашем резерве сейчас нет техники, которую можно модифицировать в: $VARIANT|H$§!"
 PRODUCTION_LINE_CONVERT_HEADER:0 "Модифицировать из резерва"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION:0 "Порядок модификации:"
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_ENTRY:0 "\n  $NUM|Y2$ ед. $VARIANT|G$ (§H$TYPE$§!) со стоимостью: "
 PRODUCTION_LINE_CONVERT_ORDER_OF_CONVERSION_FREE_ENTRY:0 "\n  $NUM|Y2$ ед. $VARIANT|G$ (§H$TYPE$§!)"
 PRODUCTION_LINE_CONVERT_RESOURCE_COST_ENTRY:0 "§H$NUM$§!£resources_strip|$FRAME$ "
 PRODUCTION_LINE_CONVERT_DESC:0 "При модификации из резерва §Hустаревшее§! или §Hзахваченное оборудование§!, находящееся в вашем резерве, будет модифицировано в измененные варианты техники, необходимые текущей производственной линии, по сниженной цене. Это действие будет выполняться до тех пор, пока резерв не опустеет."
 PRODUCTION_LINE_CONVERT_SPEED_TOTAL:0 "Скорость модификации: §G+§!$SPD|G%0$"
 PRODUCTION_LINE_CONVERT_SPEED_BASE:0 "Базовое значение: $VAL|Y0%$"
 PRODUCTION_LINE_CONVERT_RES_NEED:0 "Ресурсы, необходимые для модификации $NAME|Y$:"
 PRODUCTION_LINE_CONVERT_RES_NEED_ENTRY:0 "\n   £resources_strip|$FRAME$: ($NEW|Y0$-$OLD|G0$)=$SUM|R0$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL_SIMPLE:0 "§HЛицензированное производство§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_TOTAL:0 "§HОбъем заводского производства по лицензии§!\nВсего: $VALUE|+%$\nРазбивка:"
 LICENSED_EQUIPMENT_TECH_SPEED_REDUCTION:0 "§YРазница между лицензированной технологией§!:\n Базовое значение: $BASE|+%$\n Итоговое значение: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_MODIFIER:0 "§YКоэффициент лицензии§!:\n Базовое значение: $BASE|+%$\n Итоговое значение: $TOTAL|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NOT_FACTION:0 "§YНе в альянсе с лицензиаром§!: $VALUE|+%$"
 LICENSED_EQUIPMENT_PRODUCTION_SPEED_NO_LICENSE:0 "§YНет действующей лицензии§!: $VALUE|+%$"
 LICENSED_PURCHASE_CIC_COST:0 "§YСтоимость лицензии§!: £civ_factory $AMOUNT|Y$"
